export const initialPaginationModel = { page: 0, pageSize: 10 };

export enum invoiceStatus {
  UNDEFINED = 'UNDEFINED',
  REGISTERED = 'REGISTERED',
  TRANSFERRED = 'TRANSFERRED',
  ASSIGNED = 'ASSIGNED',
  CENSORED = 'CENSORED',
  CHECKED = 'CHECKED',
  RECEIVED = 'RECEIVED',
  OUTED = 'OUTED',
  COMPLETED = 'COMPLETED',
}

export enum invoiceActions {
  REGISTER = 'REGISTER',
  UNREGISTER = 'UNREGISTER',
  TRANSFER = 'TRANSFER',
  UNTRANSFER = 'UNTRANSFER',
  ASSIGN = 'ASSIGN',
  UNASSIGN = 'UNASSIGN',
  CENSOR = 'CENSOR',
  UNCENSOR = 'UNCENSOR',
  CHECK = 'CHECK',
  UNCHECK = 'UNCHECK',
  RECEIVE = 'RECEIVE',
  UNRECEIVE = 'UNRECEIVE',
  OUT = 'OUT',
  UNOUT = 'UNOUT',
  COMPLETE = 'COMPLETE',
  UNCOMPLETE = 'UNCOMPLETE',
}

export enum fileTypes {
  ALL = 'ALL',
  EMAIL = 'EMAIL',
  FTP = 'FTP',
  OUTFTP = 'OUTFTP',
}

export enum findCategory {
  ALL = 'ALL',
  DEP = 'DEP',
  MINE = 'MINE',
}

export enum roles {
  ADMIN = 'ADMIN',

  // USERS
  USERS_VIEW = 'USERS_VIEW',
  USERS_CREATE = 'USERS_CREATE',
  USERS_EDIT = 'USERS_EDIT',
  USERS_DELETE = 'USERS_DELETE',

  // CODES
  CODES_VIEW = 'CODES_VIEW',
  CODES_CREATE = 'CODES_CREATE',
  CODES_EDIT = 'CODES_EDIT',
  CODES_DELETE = 'CODES_DELETE',

  // SETTINGS
  SETTINGS_VIEW = 'SETTINGS_VIEW',
  SETTINGS_CREATE = 'SETTINGS_CREATE',
  SETTINGS_EDIT = 'SETTINGS_EDIT',
  SETTINGS_DELETE = 'SETTINGS_DELETE',

  // RECEIPT
  RECEIPT_VIEW = 'RECEIPT_VIEW',
  RECEIPT_REGISTER = 'RECEIPT_REGISTER',
  RECEIPT_TRANSFER = 'RECEIPT_TRANSFER',
  RECEIPT_OUT = 'RECEIPT_OUT',

  // DEP
  DEP_VIEW = 'DEP_VIEW',
  DEP_ASSIGN = 'DEP_ASSIGN',
  DEP_RECEIVE = 'DEP_RECEIVE',

  // CENSOR
  PERSONAL_VIEW = 'PERSONAL_VIEW',
  PERSONAL_CENSOR = 'PERSONAL_CENSOR',
  PERSONAL_CHECK = 'PERSONAL_CHECK',

  // TOTAL
  TOTAL_VIEW = 'TOTAL_VIEW',

  // STATISTIC
  PEOPLE_VIEW = 'PEOPLE_VIEW',
  PUB_VIEW = 'PUB_VIEW',
  FLOW_VIEW = 'FLOW_VIEW',
}

export const compressionFileExtensions = ['rar', 'zip', '7z'];
export enum invoiceFlagTypes {
  PART = 'PART',
}
